export const endpoints = {
  home: {
    summary: '/home',
    heroSlides: '/home/hero-slides',
    dashboardHeroSlides: '/home/hero-slides/dashboard/',
    dashboardHeroSlideDetail: (slideId: string | number) => `/home/hero-slides/dashboard/${encodeURIComponent(String(slideId))}/`,
    trendingSearches: '/search/trending',
    featuredCategories: '/categories',
    testimonials: '/testimonials',
    genreHighlights: '/home/genres/highlights',
  },
  books: {
    list: '/books/',
    search: '/books/search/',
    categories: '/books/categories/',
    dashboardList: '/books/dashboard/',
    dashboardCategories: '/books/dashboard/categories/',
    authorDetail: (authorSlug: string) => `/books/authors/${authorSlug}/`,
    authorOfWeek: '/books/author-of-the-week/',
    booksOfYear: '/books/books-of-the-year/',
    bestSelling: '/books/best-selling/',
    detail: (bookSlug: string) => `/books/${bookSlug}/`,
    likes: (bookSlug: string) => `/books/${bookSlug}/likes/`,
  },
  contact: {
    info: '/contact/info',
    subjects: '/contact/subjects',
    availability: '/contact/availability',
    messages: '/contact/messages',
    dashboardMessages: '/contact/dashboard/messages',
    messageDetail: (messageId: string) => `/contact/messages/${messageId}`,
  },
  auth: {
    login: '/auth/login/',
  },
  dashboard: {
    overview: '/dashboard/overview/',
    revenue: '/dashboard/revenue/',
    retention: '/dashboard/retention/',
    leads: '/dashboard/leads/',
    orders: '/dashboard/orders/',
    books: '/dashboard/books/',
    notifications: '/dashboard/notifications/',
    calendar: '/dashboard/calendar/',
    favorites: '/dashboard/favorites/',
  },
  search: {
    suggestions: '/search/suggestions',
  },
  business: {
    deliverySettings: '/business/delivery-settings/',
    dashboardDeliverySettings: '/business/delivery-settings/dashboard/',
  },
  cart: {
    summary: '/cart/summary',
  },
  orders: {
    list: '/orders/',
    create: '/orders/',
  },
  printing: {
    dashboardOrders: '/printing/dashboard/orders/',
    dashboardOrderDetail: (orderId: string) => `/printing/dashboard/orders/${encodeURIComponent(orderId)}/`,
    dashboardOrderStatus: (orderId: string) => `/printing/dashboard/orders/${encodeURIComponent(orderId)}/status/`,
    dashboardPricing: '/printing/dashboard/pricing/',
    dashboardItemPricing: (itemId: string) => `/printing/dashboard/items/${encodeURIComponent(itemId)}/pricing/`,
  },
} as const;
